apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secure-api
  namespace: secure-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: secure-api
    spec:
      containers:
        - name: secure-api
          image: secure-api:v1
          envFrom:
            - secretRef:
                name: secret-secure-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1