apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-secure-api
  namespace: secure-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: deploy-secure-api
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource