apiVersion: v1
kind: Service
metadata:
  name: svc-secure-api
  namespace: secure-api
spec:
  selector:
    app: secure-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
